# Generated by Django 6.0.6 on 2026-06-05 22:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('carrier', models.CharField(blank=True, default='', max_length=200)),
                ('default_truck_number', models.CharField(blank=True, default='', max_length=40)),
                ('home_terminal', models.CharField(blank=True, default='', max_length=120)),
                ('main_office', models.CharField(blank=True, default='', max_length=200)),
                ('current_cycle_used_hrs', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('on_duty_hrs', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('driving_hrs', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('generated', 'Generated')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_history', to='trip.driver')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('driver', 'date', 'source')},
            },
        ),
    ]
