# Generated by Django 6.0.6 on 2026-06-05 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=200)),
                ('pickup_location', models.CharField(max_length=200)),
                ('dropoff_location', models.CharField(max_length=200)),
                ('current_cycle_used_hrs', models.FloatField(default=0.0)),
                ('use_sleeper_berth', models.BooleanField(default=True)),
                ('total_miles', models.FloatField()),
                ('total_days', models.IntegerField()),
                ('total_driving_hrs', models.FloatField()),
                ('total_on_duty_hrs', models.FloatField()),
                ('final_cycle_used', models.FloatField()),
                ('recap_approximate', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='trip.driver')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='trip_trip_created_bcacd8_idx')],
            },
        ),
    ]
